'use strict';

const fs = require('fs/promises');
const path = require('path');
const { version } = require('../package.json');
const { redactObject } = require('./redactor');
const { resolveAuthorizedWorkspacePath } = require('./product/workspace-authority');

async function exportDiagnostics(rootPath, report, options = {}) {
  if (options.workspaceTrusted !== true) {
    throw new Error('Workspace Trust is required for diagnostic export.');
  }

  const exportDir = await resolveAuthorizedWorkspacePath(rootPath, options.exportPath || '.lan-vscode');
  await fs.mkdir(exportDir, { recursive: true });

  const sanitized = redactObject({
    tool: 'Living Architecture Nodes VS Code Extension',
    version,
    report
  });

  const jsonPath = path.join(exportDir, 'living-architecture-diagnostic.json');
  const markdownPath = path.join(exportDir, 'living-architecture-diagnostic.md');
  await fs.writeFile(jsonPath, JSON.stringify(sanitized, null, 2), 'utf8');
  await fs.writeFile(markdownPath, createMarkdownSummary(report), 'utf8');

  return { jsonPath, markdownPath };
}

function createMarkdownSummary(report) {
  const lines = [];
  lines.push('# Living Architecture Nodes Diagnostic Summary');
  lines.push('');
  lines.push(`Generated: ${report.generatedAt}`);
  lines.push('');
  lines.push('## Status');
  lines.push('');
  lines.push(`- Status: **${report.status.toUpperCase()}**`);
  lines.push(`- Health score: **${report.healthScore}/100**`);
  lines.push(`- Source files scanned: ${report.summary.sourceFileCount}`);
  lines.push(`- Node files found: ${report.summary.nodeFileCount}`);
  lines.push(`- Missing required artifacts: ${report.summary.missingRequiredCount}`);
  lines.push(`- Missing nodes: ${report.summary.missingNodeCount}`);
  lines.push(`- Dirty nodes: ${report.summary.dirtyNodeCount}`);
  lines.push(`- Orphan nodes: ${report.summary.orphanNodeCount}`);
  lines.push('');
  addSection(lines, 'Missing required artifacts', report.missingRequired.map((x) => `- ${x}`));
  addSection(lines, 'Missing node files', report.missingNodes.map((x) => `- ${x.sourcePath} needs ${x.nodePath}`));
  addSection(lines, 'Dirty node risks', report.dirtyNodes.map((x) => `- ${x.nodePath}: ${x.reason}`));
  addSection(lines, 'Orphan node files', report.orphanNodes.map((x) => `- ${x.nodePath}`));
  lines.push('## Suggested investigation order');
  lines.push('');
  if (report.missingRequired.length || report.missingNodes.length || report.dirtyNodes.length) {
    lines.push('1. Resolve missing required artifacts and missing node files.');
    lines.push('2. Review dirty node risks before editing affected source files.');
  } else {
    lines.push('1. No immediate architecture-memory blockers detected.');
  }
  lines.push('2. Review `ARCH.md` for intent vs reality gaps.');
  lines.push('3. Review `NERVE.md` for cascade risks and recurring bug patterns.');
  lines.push('4. Update `CHANGELOG.node.md` after cross-cutting changes.');
  lines.push('');
  lines.push('Generated by Living Architecture Nodes VS Code Extension.');
  lines.push('');
  lines.push('Developed by Altru.dev — Code For Humanity.');
  return lines.join('\n');
}

function addSection(lines, title, items) {
  lines.push(`## ${title}`);
  lines.push('');
  if (items.length) lines.push(...items);
  else lines.push('None');
  lines.push('');
}

module.exports = { exportDiagnostics, createMarkdownSummary };
