'use strict';

function createNodeTemplate({ sourcePath, nodePath, generatedBy }) {
  const now = new Date().toISOString();
  return `# Node: ${sourcePath}

Generated: ${now}  
Generated by: ${generatedBy}

## Static layer

### Purpose

Describe what \`${sourcePath}\` is responsible for.

### Responsibility boundary

This module is responsible for:

- TODO

This module is not responsible for:

- TODO

### Dependencies

This module calls or depends on:

- TODO

### Dependents

This module is called by or affects:

- TODO

### Contracts

Expected inputs:

- TODO

Expected outputs:

- TODO

Side effects:

- TODO

## Dynamic layer

### Current stability state

Under active change.

### Recent mutations

- ${now}: Created companion node for \`${sourcePath}\`.

### Known fragile points

- TODO

### Interaction warnings

- TODO

### Performance observations

- TODO

### Security notes

- TODO

## Diagnostic layer

### Past bug patterns

None recorded yet.

### Near misses

None recorded yet.

### Regression triggers

- TODO

### Suspected hidden coupling

- TODO
`;
}

module.exports = { createNodeTemplate };
